"""cities

Revision ID: 0004_cities
Revises: 0003_listings_photos_likes
Create Date: 2026-06-04 07:40:28.405641
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_cities"
down_revision: str | None = "0003_listings_photos_likes"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("wave", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cities")),
    )
    # ### end Alembic commands ###

    # Seed the 10 launch cities (PRD §9). Rollout gated per-city by `enabled`;
    # Moscow + SPb (wave 1) are live, the rest flip on as cities roll out.
    cities = sa.table(
        "cities",
        sa.column("id", sa.String),
        sa.column("name", sa.String),
        sa.column("population", sa.Integer),
        sa.column("wave", sa.Integer),
        sa.column("enabled", sa.Boolean),
    )
    op.bulk_insert(
        cities,
        [
            {"id": "msk", "name": "Москва", "population": 13150000, "wave": 1, "enabled": True},
            {
                "id": "spb",
                "name": "Санкт-Петербург",
                "population": 5600000,
                "wave": 1,
                "enabled": True,
            },
            {
                "id": "nsk",
                "name": "Новосибирск",
                "population": 1630000,
                "wave": 2,
                "enabled": False,
            },
            {
                "id": "ekb",
                "name": "Екатеринбург",
                "population": 1540000,
                "wave": 2,
                "enabled": False,
            },
            {"id": "kzn", "name": "Казань", "population": 1320000, "wave": 2, "enabled": False},
            {
                "id": "krsk",
                "name": "Красноярск",
                "population": 1210000,
                "wave": 3,
                "enabled": False,
            },
            {
                "id": "nnv",
                "name": "Нижний Новгород",
                "population": 1200000,
                "wave": 3,
                "enabled": False,
            },
            {"id": "chel", "name": "Челябинск", "population": 1180000, "wave": 3, "enabled": False},
            {"id": "ufa", "name": "Уфа", "population": 1160000, "wave": 3, "enabled": False},
            {"id": "smr", "name": "Самара", "population": 1160000, "wave": 3, "enabled": False},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cities")
    # ### end Alembic commands ###
