"""deals payments payouts ledger

Revision ID: 0005_deals_escrow
Revises: 0004_cities
Create Date: 2026-06-04 08:11:59.786786
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005_deals_escrow"
down_revision: str | None = "0004_cities"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deals",
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("buyer_id", sa.Uuid(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("amount_kopecks", sa.BigInteger(), nullable=False),
        sa.Column("commission_kopecks", sa.BigInteger(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'created'"), nullable=False
        ),
        sa.Column("delivery_method", sa.String(length=16), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_method IN ('self_pickup','courier')",
            name=op.f("ck_deals_delivery_method_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('created','paid_held','released','refunded','disputed','cancelled')",
            name=op.f("ck_deals_status_valid"),
        ),
        sa.CheckConstraint("amount_kopecks > 0", name=op.f("ck_deals_amount_positive")),
        sa.ForeignKeyConstraint(
            ["buyer_id"], ["users.id"], name=op.f("fk_deals_buyer_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_deals_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["users.id"], name=op.f("fk_deals_seller_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deals")),
    )
    op.create_index(op.f("ix_deals_buyer_id"), "deals", ["buyer_id"], unique=False)
    op.create_index(op.f("ix_deals_listing_id"), "deals", ["listing_id"], unique=False)
    op.create_index(op.f("ix_deals_seller_id"), "deals", ["seller_id"], unique=False)
    op.create_index(op.f("ix_deals_status"), "deals", ["status"], unique=False)
    op.create_table(
        "ledger_entries",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("amount_kopecks", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('hold','commission','payout','refund')",
            name=op.f("ck_ledger_entries_kind_valid"),
        ),
        sa.CheckConstraint("amount_kopecks > 0", name=op.f("ck_ledger_entries_amount_positive")),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deals.id"],
            name=op.f("fk_ledger_entries_deal_id_deals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
    )
    op.create_index(op.f("ix_ledger_entries_deal_id"), "ledger_entries", ["deal_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("yk_payment_id", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_payments_deal_id_deals"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("idempotency_key", name="idempotency_key"),
        sa.UniqueConstraint("yk_payment_id", name=op.f("uq_payments_yk_payment_id")),
    )
    op.create_index(op.f("ix_payments_deal_id"), "payments", ["deal_id"], unique=False)
    op.create_table(
        "payouts",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("yk_payout_id", sa.String(length=64), nullable=True),
        sa.Column("payout_target_masked", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("fiscal_receipt_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_payouts_deal_id_deals"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payouts")),
        sa.UniqueConstraint("yk_payout_id", name=op.f("uq_payouts_yk_payout_id")),
    )
    op.create_index(op.f("ix_payouts_deal_id"), "payouts", ["deal_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payouts_deal_id"), table_name="payouts")
    op.drop_table("payouts")
    op.drop_index(op.f("ix_payments_deal_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_ledger_entries_deal_id"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(op.f("ix_deals_status"), table_name="deals")
    op.drop_index(op.f("ix_deals_seller_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_listing_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_buyer_id"), table_name="deals")
    op.drop_table("deals")
    # ### end Alembic commands ###
