"""reviews

Revision ID: 0007_reviews
Revises: 0006_audit_log
Create Date: 2026-06-04 10:01:01.750636
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007_reviews"
down_revision: str | None = "0006_audit_log"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "moderation_status",
            sa.String(length=16),
            server_default=sa.text("'visible'"),
            nullable=False,
        ),
        sa.Column("text", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "moderation_status IN ('visible','held')",
            name=op.f("ck_reviews_moderation_status_valid"),
        ),
        sa.CheckConstraint("score BETWEEN 1 AND 5", name=op.f("ck_reviews_score_range")),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_reviews_author_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_reviews_deal_id_deals"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_id"], ["users.id"], name=op.f("fk_reviews_target_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("deal_id", "author_id", name="deal_author"),
    )
    op.create_index(op.f("ix_reviews_author_id"), "reviews", ["author_id"], unique=False)
    op.create_index(op.f("ix_reviews_deal_id"), "reviews", ["deal_id"], unique=False)
    op.create_index(op.f("ix_reviews_target_id"), "reviews", ["target_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_target_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_deal_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_author_id"), table_name="reviews")
    op.drop_table("reviews")
    # ### end Alembic commands ###
