"""photo phash

Revision ID: 0011_photo_phash
Revises: 0010_dsr
Create Date: 2026-06-04 11:33:37.129650
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011_photo_phash"
down_revision: str | None = "0010_dsr"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photos", sa.Column("phash", sa.String(length=16), nullable=True))
    op.create_index(op.f("ix_photos_phash"), "photos", ["phash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_photos_phash"), table_name="photos")
    op.drop_column("photos", "phash")
    # ### end Alembic commands ###
