"""listing messages

Revision ID: 0013_listing_messages
Revises: 0012_notifications
Create Date: 2026-06-04 13:21:52.313166
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0013_listing_messages"
down_revision: str | None = "0012_notifications"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listing_messages",
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("buyer_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'visible'"), nullable=False
        ),
        sa.Column("body", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('visible','held')", name=op.f("ck_listing_messages_lmessage_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["users.id"],
            name=op.f("fk_listing_messages_buyer_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_messages_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
            name=op.f("fk_listing_messages_sender_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_messages")),
    )
    op.create_index(
        op.f("ix_listing_messages_buyer_id"), "listing_messages", ["buyer_id"], unique=False
    )
    op.create_index(
        op.f("ix_listing_messages_listing_id"), "listing_messages", ["listing_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listing_messages_listing_id"), table_name="listing_messages")
    op.drop_index(op.f("ix_listing_messages_buyer_id"), table_name="listing_messages")
    op.drop_table("listing_messages")
    # ### end Alembic commands ###
