"""user reports

Revision ID: 0014_user_reports
Revises: 0013_listing_messages
Create Date: 2026-06-04 13:47:18.838953
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0014_user_reports"
down_revision: str | None = "0013_listing_messages"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_reports",
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=8), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=8), server_default=sa.text("'open'"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open','reviewed')", name=op.f("ck_user_reports_report_status_valid")
        ),
        sa.CheckConstraint(
            "target_type IN ('listing','user')", name=op.f("ck_user_reports_report_target_valid")
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
            name=op.f("fk_user_reports_reporter_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_reports")),
    )
    op.create_index(
        op.f("ix_user_reports_reporter_id"), "user_reports", ["reporter_id"], unique=False
    )
    op.create_index(op.f("ix_user_reports_status"), "user_reports", ["status"], unique=False)
    op.create_index(op.f("ix_user_reports_target_id"), "user_reports", ["target_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_reports_target_id"), table_name="user_reports")
    op.drop_index(op.f("ix_user_reports_status"), table_name="user_reports")
    op.drop_index(op.f("ix_user_reports_reporter_id"), table_name="user_reports")
    op.drop_table("user_reports")
    # ### end Alembic commands ###
