"""user notif settings

Revision ID: 0015_notif_settings
Revises: 0014_user_reports
Create Date: 2026-06-04 13:52:23.522515
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0015_notif_settings"
down_revision: str | None = "0014_user_reports"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("notif_messages", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("notif_marketing", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notif_marketing")
    op.drop_column("users", "notif_messages")
    # ### end Alembic commands ###
