"""fraud signals + risk score

Revision ID: 0017_fraud
Revises: 0016_support_tickets
Create Date: 2026-06-04 14:03:31.297763
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0017_fraud"
down_revision: str | None = "0016_support_tickets"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fraud_signals",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=8), server_default=sa.text("'open'"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open','reviewed')", name=op.f("ck_fraud_signals_fraud_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_fraud_signals_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraud_signals")),
        sa.UniqueConstraint("user_id", "type", name="fraud_user_type"),
    )
    op.create_index(op.f("ix_fraud_signals_status"), "fraud_signals", ["status"], unique=False)
    op.create_index(op.f("ix_fraud_signals_user_id"), "fraud_signals", ["user_id"], unique=False)
    op.add_column(
        "users", sa.Column("risk_score", sa.Integer(), server_default=sa.text("0"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "risk_score")
    op.drop_index(op.f("ix_fraud_signals_user_id"), table_name="fraud_signals")
    op.drop_index(op.f("ix_fraud_signals_status"), table_name="fraud_signals")
    op.drop_table("fraud_signals")
    # ### end Alembic commands ###
