"""deal pickup address enc

Revision ID: 0018_pickup_address
Revises: 0017_fraud
Create Date: 2026-06-04 14:11:57.431543
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0018_pickup_address"
down_revision: str | None = "0017_fraud"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deals", sa.Column("pickup_address_enc", sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deals", "pickup_address_enc")
    # ### end Alembic commands ###
